<?php

/**
 * This is the model base class for the table "tarefas".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tarefas".
 *
 * Columns in table "tarefas" available as properties of the model,
 * followed by relations of table "tarefas" available as properties of the model.
 *
 * @property string $ID_Tarefa
 * @property string $Titulo
 * @property string $idUsuario
 * @property string $Privacidade
 * @property string $Descricao
 * @property string $idTipo
 * @property string $Status
 * @property string $Data_Conclusao
 * @property string $Data_Criacao
 * @property string $Data_Modificacao
 *
 * @property Usuarios $idUsuario0
 * @property TipoTarefa $idTipo0
 */
abstract class BaseTarefas extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tarefas';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tarefas|Tarefases', $n);
	}

	public static function representingColumn() {
		return 'Titulo';
	}

	public function rules() {
		return array(
			array('Titulo, Privacidade, Descricao, idTipo, Status', 'required'),
			array('Titulo', 'length', 'max'=>150),
			array('idUsuario, idTipo', 'length', 'max'=>10),
			array('Privacidade', 'length', 'max'=>7),
			array('Status', 'length', 'max'=>9),
			array('Data_Conclusao, Data_Criacao, Data_Modificacao', 'safe'),
			array('idUsuario, Data_Conclusao, Data_Criacao, Data_Modificacao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('ID_Tarefa, Titulo, idUsuario, Privacidade, Descricao, idTipo, Status, Data_Conclusao, Data_Criacao, Data_Modificacao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idUsuario0' => array(self::BELONGS_TO, 'Usuarios', 'idUsuario'),
			'idTipo0' => array(self::BELONGS_TO, 'TipoTarefa', 'idTipo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ID_Tarefa' => Yii::t('app', 'Id Tarefa'),
			'Titulo' => Yii::t('app', 'Titulo'),
			'idUsuario' => null,
			'Privacidade' => Yii::t('app', 'Privacidade'),
			'Descricao' => Yii::t('app', 'Descricao'),
			'idTipo' => null,
			'Status' => Yii::t('app', 'Status'),
			'Data_Conclusao' => Yii::t('app', 'Data Conclusao'),
			'Data_Criacao' => Yii::t('app', 'Data Criacao'),
			'Data_Modificacao' => Yii::t('app', 'Data Modificacao'),
			'idUsuario0' => null,
			'idTipo0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ID_Tarefa', $this->ID_Tarefa, true);
		$criteria->compare('Titulo', $this->Titulo, true);
		$criteria->compare('idUsuario', $this->idUsuario);
		$criteria->compare('Privacidade', $this->Privacidade, true);
		$criteria->compare('Descricao', $this->Descricao, true);
		$criteria->compare('idTipo', $this->idTipo);
		$criteria->compare('Status', $this->Status, true);
		$criteria->compare('Data_Conclusao', $this->Data_Conclusao, true);
		$criteria->compare('Data_Criacao', $this->Data_Criacao, true);
		$criteria->compare('Data_Modificacao', $this->Data_Modificacao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

}