<?php

/**
 * This is the model base class for the table "tipo_tarefa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoTarefa".
 *
 * Columns in table "tipo_tarefa" available as properties of the model,
 * followed by relations of table "tipo_tarefa" available as properties of the model.
 *
 * @property string $ID_Tipo_Tarefa
 * @property string $Nome
 * @property string $Data_Criacao
 * @property string $Data_Modificacao
 *
 * @property Tarefas[] $tarefases
 */
abstract class BaseTipoTarefa extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tipo_tarefa';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TipoTarefa|TipoTarefas', $n);
	}

	public static function representingColumn() {
		return 'Nome';
	}

	public function rules() {
		return array(
			array('Nome', 'required'),
			array('Nome', 'length', 'max'=>150),
			array('Nome', 'unique'),
			array('Data_Criacao, Data_Modificacao', 'safe'),
			array('Data_Criacao, Data_Modificacao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('ID_Tipo_Tarefa, Nome, Data_Criacao, Data_Modificacao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tarefases' => array(self::HAS_MANY, 'Tarefas', 'idTipo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ID_Tipo_Tarefa' => Yii::t('app', 'Id Tipo Tarefa'),
			'Nome' => Yii::t('app', 'Nome'),
			'Data_Criacao' => Yii::t('app', 'Data Criacao'),
			'Data_Modificacao' => Yii::t('app', 'Data Modificacao'),
			'tarefases' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ID_Tipo_Tarefa', $this->ID_Tipo_Tarefa, true);
		$criteria->compare('Nome', $this->Nome, true);
		$criteria->compare('Data_Criacao', $this->Data_Criacao, true);
		$criteria->compare('Data_Modificacao', $this->Data_Modificacao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}